=== HTW-ALADIN/ALADIN-Services/services/graph-rewriting-service/src/schemas/request-transform.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "request-transform.schema.json",
	"title": "Graph Rewriting Request Schema",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"hostgraph": {
			"$ref": "graph.schema.json"
		},
		"rules": {
			"type": "array",
			"items": {
				"$ref": "rewrite-rule.schema.json"
			}
		},
		"sequence": {
			"type": "array",
			"items": {
				"anyOf": [
					{
						"$ref": "run-config.schema.json"
					},
					{
						"$ref": "run-nested-config.schema.json"
					}
				]
			}
		},
		"options": {
			"type": "object",
			"properties": {
				"returnHistory": {
					"description": "If set to true, the resultset will include the exported hostgraph after each rewriting step in chronological order.",
					"type": "boolean",
					"default": false
				}
			},
			"additionalProperties": false
		}
	},
	"required": ["hostgraph"]
}

=== HTW-ALADIN/ALADIN-Services/services/graph-rewriting-service/examples/data/usecases/epc_v2.json
{
    "hostgraph": {
        "options": {
            "type": "directed"
        },
        "nodes": [
            {
                "key": "Start",
                "attributes": {
                    "label": "Start",
                    "type": "Event"
                }
            },
            {
                "key": "Ende",
                "attributes": {
                    "label": "Ende",
                    "type": "Event"
                }
            }
        ],
        "edges": [
            {
                "key": "StartToEnde",
                "source": "Start",
                "target": "Ende",
                "attributes": {}
            }
        ]
    },
    "rules": [
        {
            "key": "add_pattern",
            "options": {
                "homomorphic": false
            },
            "patternGraph": {
                "options": {
                    "type": "directed"
                },
                "nodes": [
                    {
                        "key": "A",
                        "attributes": {}
                    },
                    {
                        "key": "B",
                        "attributes": {}
                    }
                ],
                "edges": [
                    {
                        "key": "aToB",
                        "source": "A",
                        "target": "B",
                        "attributes": {}
                    }
                ]
            },
            "replacementGraph": {
                "options": {
                    "type": "directed"
                },
                "nodes": [
                    {
                        "key": "A",
                        "attributes": {}
                    },
                    {
                        "key": "Pattern",
                        "attributes": {
                            "label": {
                                "type": "randexp",
                                "args": {
                                    "pattern": "(AND-Rhombus|OR-Rhombus|XOR-Rhombus)",
                                    "options": {}
                                }
                            },
                            "patternId": {
                                "type": "faker",
                                "args": {
                                    "module": "string",
                                    "method": "uuid"
                                }
                            },
                            "type": "pattern"
                        }
                    },
                    {
                        "key": "B",
                        "attributes": {}
                    }
                ],
                "edges": [
                    {
                        "key": "AToPattern",
                        "source": "A",
                        "target": "Pattern",
                        "attributes": {}
                    },
                    {
                        "key": "PatternToB",
                        "source": "Pattern",
                        "target": "B",
                        "attributes": {}
                    }
                ]
            }
        },
        {
            "key": "replace_pattern_with_gate",
            "options": {
                "homomorphic": false
            },
            "patternGraph": {
                "options": {
                    "type": "directed"
                },
                "nodes": [
                    {
                        "key": "A",
                        "attributes": {}
                    },
                    {
                        "key": "Pattern",
                        "attributes": {
                            "type": "pattern"
                        }
                    },
                    {
                        "key": "B",
                        "attributes": {}
                    }
                ],
                "edges": [
                    {
                        "key": "AToPattern",
                        "source": "A",
                        "target": "Pattern",
                        "attributes": {}
                    },
                    {
                        "key": "PatternToB",
                        "source": "Pattern",
                        "target": "B",
                        "attributes": {}
                    }
                ]
            },
            "replacementGraph": {
                "options": {
                    "type": "directed"
                },
                "nodes": [
                    {
                        "key": "A",
                        "attributes": {}
                    },
                    {
                        "key": "Gate1",
                        "attributes": {
                            "type": "Gate",
                            "label": {
                                "type": "jsonLogic",
                                "args": {
                                    "rule": {
                                        "if": [
                                            {
                                                "==": [
                                                    "$.nodes.[?(@.key === 'Pattern')].attributes.label",
                                                    "AND-Rhombus"
                                                ]
                                            },
                                            "AND",
                                            {
                                                "==": [
                                                    "$.nodes.[?(@.key === 'Pattern')].attributes.label",
                                                    "OR-Rhombus"
                                                ]
                                            },
                                            "OR",
                                            {
                                                "==": [
                                                    "$.nodes.[?(@.key === 'Pattern')].attributes.label",
                                                    "XOR-Rhombus"
                                                ]
                                            },
                                            "XOR",
                                            {
                                                "var": ""
                                            }
                                        ]
                                    }
                                }
                            },
                            "gateType": "open",
                            "patternId": {
                                "type": "jsonLogic",
                                "args": {
                                    "rule": {
                                        "var": "$.nodes.[?(@.key === 'Pattern')].attributes.patternId"
                                    }
                                }
                            }
                        }
                    },
                    {
                        "key": "Gate2",
                        "attributes": {
                            "type": "Gate",
                            "label": {
                                "type": "jsonLogic",
                                "args": {
                                    "rule": {
                                        "if": [
                                            {
                                                "==": [
                                                    "$.nodes.[?(@.key === 'Pattern')].attributes.label",
                                                    "AND-Rhombus"
                                                ]
                                            },
                                            "AND",
                                            {
                                                "==": [
                                                    "$.nodes.[?(@.key === 'Pattern')].attributes.label",
                                                    "OR-Rhombus"
                                                ]
                                            },
                                            "OR",
                                            {
                                                "==": [
                                                    "$.nodes.[?(@.key === 'Pattern')].attributes.label",
                                                    "XOR-Rhombus"
                                                ]
                                            },
                                            "XOR",
                                            {
                                                "var": ""
                                            }
                                        ]
                                    }
                                }
                            },
                            "gateType": "closed",
                            "patternId": {
                                "type": "jsonLogic",
                                "args": {
                                    "rule": {
                                        "var": "$.nodes.[?(@.key === 'Pattern')].attributes.patternId"
                                    }
                                }
                            }
                        }
                    },
                    {
                        "key": "B",
                        "attributes": {}
                    }
                ],
                "edges": [
                    {
                        "key": "AToGate1",
                        "source": "A",
                        "target": "Gate1",
                        "attributes": {
                            "patternId": {
